name: cognifeed_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.2
  cached_network_image: ^2.0.0
  flutter_icons: ^1.0.0+1
  image_cropper: ^1.2.1
  image_picker: ^0.6.3+4
  flutter_datetime_picker: ^1.3.4
  cupertino_icons: ^0.1.3
  flutter_bloc: ^3.2.0
  meta: ^1.1.8
  http: ^0.12.0+4
  dio: ^3.0.9
  shared_preferences: ^0.5.6+2
  string_validator: ^0.1.3
  flare_flutter: ^2.0.1
  webview_flutter: ^0.3.19+9
  share: ^0.6.3+6
  clipboard_manager: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/flare/
