name: cognifeed_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.15.0

  cupertino_icons: ^0.1.2
  flutter_bloc: ^3.1.0
  meta: ^1.1.8
  http: ^0.12.0+3
  shared_preferences: ^0.5.6
  string_validator: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: PoorRichard
      fonts:
        - asset: fonts/PoorRichard.TTF

    - family: SegoeUI
      fonts:
        - asset: fonts/Segoe-UI.ttf
        - asset: fonts/Segoe-UI-Italic.ttf
          style: italic
        - asset: fonts/Segoe-UI-Bold.ttf
          weight: 700
